<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Observation.Core</RootNamespace>
    <AssemblyName>Observation.Core</AssemblyName>
    <PackageId>Observation.Core</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/lancer1977/observation-core</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
</Project>
